title: Status Demo
# logo: https://example.com/logo.png
language: es
report: https://github.com/salteadorneo/status/issues/new

checks:
  - name: Web
    url: https://salteadorneo.github.io/status/
  
  - name: Example Service
    url: https://example.com/health
